#!/usr/bin/env node

var argv = require('optimist').argv;
var fs = require('fs')
var blockName = argv._[0]
var blockPath = 'b'
var blockJade = 'b/blocks.jade'
var blockStylus = 'b/blocks.styl'


fs.lstat( blockPath + '/' + blockName, function(err, stats) {
    if (!err && stats.isDirectory()) {
        throw('Block exits');
    }
});

fs.mkdir( blockPath + '/' + blockName, function(err) {
    if (err) throw err;
});

fs.mkdir( blockPath + '/' + blockName + '/images', function(err) {
    if (err) throw err;
});

fs.writeFile( blockPath + '/' + blockName + '/' + blockName + '.coffe','', function(err) {
    if (err) throw err;
});
fs.writeFile( blockPath + '/' + blockName + '/' + blockName + '.styl','', function(err) {
    if (err) throw err;
});
fs.writeFile( blockPath + '/' + blockName + '/' + blockName + '.ie.styl','', function(err) {
    if (err) throw err;
});
fs.writeFile( blockPath + '/' + blockName + '/' + blockName + '.ie7.styl','', function(err) {
    if (err) throw err;
});
fs.writeFile( blockPath + '/' + blockName + '/' + blockName + '.jade','mixin' + blockName + '(args)\n', function(err) {
    if (err) throw err;
});
fs.writeFile( blockPath + '/' + blockName + '/' + blockName + '.yaml','', function(err) {
    if (err) throw err;
});
fs.writeFile( blockPath + '/' + blockName + '/' + 'jquery.' +  blockName + '.js','', function(err) {
    if (err) throw err;
});


fs.appendFile(blockJade,'include ' + blockName + '/' + blockName + '\n', function (err) {
  if (err) throw err;
  console.log('Block' + blockName + 'add to jade');
});

fs.appendFile(blockStylus,'@import "' + blockName + '/' + blockName + '"\n', function (err) {
  if (err) throw err;
  console.log('Block' + blockName + 'add to jade');
});